ServerEvents.recipes((event) => {
  let Array = [
    "alchemistry:atomizer",
    "alchemistry:compactor",
    "alchemistry:combiner",
    "alchemistry:dissolver",
    "alchemistry:liquifier",
    "anvilcraft:heater",
    "anvilcraft:ruby_laser",
    "anvilcraft:ruby_prism",
    "anvilcraft:impact_pile",
    "create:andesite_alloy",
    "anvilcraft:charge_collector",
    "create_dd:crafting_inductive_mechanism2",
    "create_dd:crafting_inductive_mechanism1",
    "create:shaft",
    "create:mechanical_press",
    "create:cogwheel",
    "create:large_cogwheel",
    "create:mechanical_mixer",
    "create:water_wheel",
    "create:large_water_wheel",
    "create:copper_valve_handle",
    "create:steam_engine",
    "create:windmill_bearing",
    "create_dd:cog_crank",
    "create_dd:kinetic_motor",
    "create_dd:accelerator_motor",
    "create:hand_crank",
    "create_dd:steel_ingot",
    "create:mechanical_saw",
    "create:sand_paper",
    "create_dd:spectral_ruby_block",
    "create:mechanical_drill",
    "create:brass_hand",
    "create:deployer",
    "create:copper_casing",
    "create:depot",
    "create_dd:spectral_ruby",
    "create:millstone",
    "minecraft:anvil",
    "create_dd:integrated_circuit",
    "create:rose_quartz",
    "create:mechanical_arm",
    "create:rotation_speed_controller",
    "create_dd:hydraulic_casing",
    "create:whisk",
    "create:chute",
    "create:andesite_funnel",
    "create:andesite_tunnel",
    "create:propeller",
    "create:encased_fan",
    "minecraft:dried_kelp_block",
    "create:brass_casing",
    "create:mechanical_crafter",
    "create_dd:lapis_alloy",
    "create:display_board",
    "create_dd:deforester_saw",
    "create:gearbox",
    "create:vertical_gearbox",
    "create:contraption_controls",
    "create:portable_storage_interface",
    "create:mechanical_roller",
    "create:wrench",
    "steampowered:steel_boiler",
    "steampowered:steel_burner",
    "steampowered:steel_large_cogwheel",
    "create_dd:2_blade_fan",
    "create_dd:4_blade_fan",
    "steampowered:bronze_cogwheel",
    "steampowered:bronze_large_cogwheel",
    "steampowered:cast_iron_cogwheel",
    "steampowered:cast_iron_large_cogwheel",
    "steampowered:steel_cogwheel",
    "create:nozzle",
    "create:basin",
    "create:sticker",
    "create:white_sail",
    "create:brass_funnel",
    "create:brass_tunnel",
    "create:adjustable_chain_gearshift",
    "create:gantry_carriage",
    "create:analog_lever",
    "create_dd:hydraulic_press",
    "create:weighted_ejector",
    "minecraft:blue_dye",
    "create:empty_blaze_burner",
    "create:smart_chute",
    "ars_nouveau:sourcestone",
    "ars_nouveau:imbuement_chamber",
    "ars_nouveau:source_gem",
    "minecraft:purple_wool",
    "minecraft:bamboo_block",
    "create_dd:leather_block",
    "ars_nouveau:arcane_core",
    "ars_nouveau:enchanting_apparatus",
    "ars_nouveau:source_gem_block",
    "ars_nouveau:agronomic_sourcelink",
    "ars_nouveau:volcanic_sourcelink",
    "ars_nouveau:alchemical_sourcelink",
    "ars_nouveau:vitalic_sourcelink",
    "ars_nouveau:mycelial_sourcelink",
    "minecraft:polished_deepslate",
    "create:railway_casing",
    "ars_nouveau:source_jar",
    "anvilcraft:flour",
    "quark:potato_crate",
    "ars_nouveau:ritual_wilden_summon",
    "ars_nouveau:ritual_brazier",
    "steampowered:cast_iron_flywheel",
    "steampowered:cast_iron_steam_engine",
    "create_dd:splashing_sail",
    "create_dd:splashing_sail",
    "create_dd:blasting_sail",
    "steampowered:steel_flywheel",
    "steampowered:alternator",
    "create_dd:haunting_sail",
    "create:extendo_grip",
    "create_dd:smoking_sail",
    "create_dd:forest_ravager",
    "create:potato_cannon",
    "steampowered:bronze_steam_engine",
    "create_dd:superheating_sail",
    "create_dd:experience_mass",
    "steampowered:bronze_flywheel",
    "steampowered:steel_steam_engine",
    "create_dd:freezing_sail",
    "create_dd:flywheel",
    "create_dd:furnace_engine",
    "create_dd:shimmer_bucket",
    "create:wand_of_symmetry",
    "create_dd:bronze_saw",
    "create_dd:bronze_drill",
    "minecraft:netherite_ingot",
    "botania:redstone_root",
    "create_dd:netherite_casing",
    "ars_nouveau:earth_essence",
    "ars_nouveau:abjuration_essence",
    "create:fluid_pipe",
    "#minecraft:wooden_slabs",
    "minecraft:barrel",
    "create:fluid_tank",
    "create:mechanical_pump",
    "create_dd:bronze_ingot",
    "create_dd:industrial_fan",
    "create_dd:rubber_sapling",
    "create_dd:raw_rubber",
    "create:belt_connector",
    "minecraft:fishing_rod",
    "#forge:bookshelves",
    "quark:oak_vertical_slab",
    "#minecraft:wooden_stairs",
    "minecraft:enchanting_table",
    "minecraft:clay_ball",
    "create_dd:chromatic_compound",
    "create:blaze_cake_base",
    "create_dd:ember_alloy",
    "create_dd:mithril_ingot",
    "anvilcraft:thermoelectric_converter",
    "create_dd:shadow_steel_casing",
    "create:goggles",
    "create_dd:experience_ingot",
    "create_enchantment_industry:hyper_experience_bottle",
    "quark:gold_bars",
    "minecraft:ender_eye",
    "minecraft:magma_cream",
    "create_dd:fallen_stargaze_singularity",
    "minecraft:tnt",
    "pneumaticcraft:reinforced_stone",
    "pneumaticcraft:reinforced_bricks",
    "pneumaticcraft:compressed_stone",
    "pneumaticcraft:reinforced_stone_slab",
    "minecraft:heavy_weighted_pressure_plate",
    "pneumaticcraft:compressed_iron_block",
    "pneumaticcraft:ingot_iron_compressed",
    "pneumaticcraft:small_tank",
    "pneumaticcraft:pressure_chamber_wall",
    "pneumaticcraft:pressure_chamber_interface",
    "pneumaticcraft:pressure_chamber_valve",
    "create_dd:industrial_casing",
    "pneumaticcraft:reinforced_brick_wall",
    "pneumaticcraft:turbine_rotor",
    "pneumaticcraft:pressure_chamber_glass",
    "pneumaticcraft:refinery",
    "pneumaticcraft:refinery_output",
    "minecraft:golden_carrot",
    "minecraft:brown_dye",
    "pneumaticcraft:speed_upgrade",
    "pneumaticcraft:thermal_lagging",
    "minecraft:redstone_lamp",
    "minecraft:green_wool",
    "quark:shingles",
    "pneumaticcraft:charging_station",
    "pneumaticcraft:pressure_gauge",
    "pneumaticcraft:air_canister",
    "pneumaticcraft:gps_tool",
    "pneumaticcraft:heat_sink",
    "pneumaticcraft:gps_tool",
    "minecraft:glass_pane",
    "create_dd:reinforcement_plating",
    "pneumaticcraft:reinforced_chest",
    "pneumaticcraft:omnidirectional_hopper",
    "pneumaticcraft:advanced_air_compressor",
    "pneumaticcraft:assembly_controller",
    "pneumaticcraft:security_upgrade",
    "pneumaticcraft:pneumatic_dynamo",
    "pneumaticcraft:flux_compressor",
    "pneumaticcraft:module_expansion_card",
    "pneumaticcraft:advanced_liquid_compressor",
    "pneumaticcraft:advanced_air_compressor",
    "pneumaticcraft:electrostatic_compressor",
    "pneumaticcraft:gas_lift",
    "pneumaticcraft:large_tank",
    "pneumaticcraft:medium_tank",
    "pneumaticcraft:liquid_compressor",
    "pneumaticcraft:manual_compressor",
    "pneumaticcraft:spawner_extractor",
    "pneumaticcraft:solar_compressor",
    "ars_nouveau:greater_experience_gem",
    "thermal:machine_crystallizer",
    "jaopca:gears.brass",
    "quark:oak_hedge",
    "minecraft:oak_wood",
    "create_dd:infacoarse_dirt",
    "create_dd:infasoul_sand",
    "create_dd:infaobsidian",
    "create_dd:spirit_log",
    "minecraft:oak_wood",
    "minecraft:black_dye",
    "integrateddynamics:drying_basin",
    "integrateddynamics:crystalized_menril_chunk",
    "integrateddynamics:crystalized_menril_block",
    "integrateddynamics:cable",
    "integrateddynamics:variable",
    "create:red_sand_paper",
    "integrateddynamics:logic_programmer",
    "pneumaticcraft:plastic_brick_white",
    "integrateddynamics:materializer",
    "anvilcraft:charger",
    "anvilcraft:capacitor_empty",
    "integrateddynamics:portable_logic_programmer",
    "integrateddynamics:variable_transformer_output",
    "integrateddynamics:variable_transformer_input",
    "integratedtunnels:part_interface_item",
    "integratedtunnels:part_interface_energy",
    "integratedtunnels:part_interface_fluid",
    "integratedtunnels:part_interface_item",
    "integrateddynamics:logic_director",
    "integrateddynamics:part_connector_mono_directional",
    "integrateddynamics:menril_fence",
    "integrateddynamics:menril_wood",
    "minecraft:recovery_compass",
    "rftoolsbase:dimensionalshard",
    "minecraft:purple_stained_glass",
    "integrateddynamics:proxy",
  ];
  Array.forEach((item) => {
    event.remove({ output: `${item}` });
  });

  event.remove({ output: "minecraft:glass", type: "smelting" });
  event.remove({ output: "#forge:glass_panes" });

  event.remove({
    output: "minecraft:clay",
    type: "anvilcraft:anvil_processing",
  });

  event.remove({
    output: "minecraft:nether_brick",
    type: "minecraft:smelting",
  });

  event.remove({ output: "minecraft:granite", input: "minecraft:quartz" });

  event.remove({
    output: "minecraft:gold_ingot",
    input: "minecraft:gold_nugget",
  });
  event.remove({
    output: "anvilcraft:zinc_ingot",
    input: "anvilcraft:zinc_nugget",
  });

  event.remove({ input: "create:copper_casing", type: "crafting_shaped" });

  event.remove({ mod: "pipez" });

  event.remove({
    output: "create:item_vault",
    input: "create_dd:overburden_casing",
  });

  event.remove({ input: "#minecraft:logs", type: "create:emptying" });

  event.remove({
    output: "create_dd:frozen_nugget",
    input: "create_dd:compound_base",
  });

  event.remove({
    output: Fluid.of("create_enchantment_industry:hyper_experience"),
  });

  event.remove({
    type: "pneumaticcraft:pressure_chamber",
  });

  event.remove({
    output: "create:portable_fluid_interface",
    input: "create_dd:sealed_mechanism",
  });

  event.remove({ type: "pneumaticcraft:explosion_crafting" });
  event.remove({
    type: "pneumaticcraft:thermo_plant",
  });
  event.remove({
    type: "pneumaticcraft:assembly_laser",
  });
  event.remove({
    type: "pneumaticcraft:assembly_drill",
  });
  event.remove({
    type: "pneumaticcraft:heat_frame_cooling",
  });

  event.remove({
    input: "minecraft:fire_charge",
    output: "#forge:ingots",
  });

  event.remove({ output: "minecraft:coarse_dirt", type: "crafting_shaped" });

  event.remove({ input: "integrateddynamics:menril_log" });

  event.remove({ output: "minecraft:redstone", type: "create:filling" });
  event.remove({ output: "minecraft:glowstone_dust", type: "create:filling" });
  event.remove({ output: "minecraft:gunpowder", type: "create:filling" });
});
